import React from 'react';
import { MarkdownPage } from '../components/MarkdownPage';

export function EvidenceEnginePage() {
  return (
    <MarkdownPage 
      title="Evidence Engine & Algorithmic Analysis" 
      subtitle="Exposing the technical architecture, mathematical models, and stylometric systems driving academic trust."
    >
      <h3>The Statistical Fallacy of Traditional AI Classifiers</h3>
      <p>
        Traditional AI detection software relies on static probabilistic classifiers designed to evaluate perplexity (a measure of how likely a sequence of words is to be generated by a language model) and burstiness (the variance in sentence length and structure). While these metrics can easily identify raw, unedited outputs from older models, they fail catastrophically when confronted with modern LLMs or human-edited text.
      </p>
      <p>
        According to peer-reviewed research highlighted in the <em>Alberta Higher Ed Policy Report</em>, traditional detectors (such as Turnitin, GPTZero, and the now-deprecated OpenAI Classifier) produce high rates of false positives. More critically, these classifiers display systemic bias. A recent MDPI technical review demonstrated that detectors consistently flag the writing of non-native English speakers (ESL students) as AI-generated. Because non-native writers tend to use simpler syntactic patterns and more predictable vocabulary, their human writing naturally displays the low perplexity and low burstiness characteristic of machine-generated prose.
      </p>

      <h3 style={{ marginTop: '32px' }}>Writing DNA: Time-Series Stylometry</h3>
      <p>
        Veritas AI's Evidence Engine is engineered to eliminate this demographic bias by shifting the paradigm from global classification to individualized comparison. We build a longitudinal, multi-dimensional <strong>Writing DNA Baseline</strong> for every student. Our engine tracks over 80 stylometric markers across four main levels of analysis:
      </p>
      <ul>
        <li><strong>Lexical Stylometry:</strong> Type-Token Ratio (TTR), word-length distributions, hapax legomena (words occurring only once), and vocabulary richness indicators (Yule's K and Simpson's D).</li>
        <li><strong>Syntactic Fingerprinting:</strong> Part-of-Speech (POS) tag sequence frequencies, dependency tree depth, coordination ratio, and sentence clause structure distributions.</li>
        <li><strong>Formatting & Structural Signatures:</strong> Paragraph indentation habits, punctuation spacing patterns, white-space usage, and document-level structural transitions.</li>
        <li><strong>Cognitive Linguistics:</strong> Passive voice frequency, prepositional phrase density, transition word usage, and nominalization rates.</li>
      </ul>
      <p>
        When a student submits an assignment, Veritas AI computes the stylometric vector of the new submission and calculates its Mahalanobis distance from the student's historical stylometric centroid. If the submission falls outside the 95% confidence interval of the baseline, the system flags the document as a "Stylometric Shift." Crucially, this flag is not an accusation of cheating; it is an analytical indicator of a significant structural deviation, prompting a pedagogical discussion.
      </p>

      <h3 style={{ marginTop: '32px' }}>The Citation Hallucination Audit</h3>
      <p>
        Generative AI models are notorious for producing "hallucinations"—fabricating realistic-sounding facts, quotes, and academic citations. UAlberta's academic code strictly forbids submitting knowingly false or fabricated content, which applies directly to students who submit papers containing hallucinated AI references.
      </p>
      <p>
        The Veritas AI Evidence Engine performs an automated, real-time citation audit on every submission. The engine:
      </p>
      <ol style={{ paddingLeft: '20px' }}>
        <li>Parses the document's bibliography and inline citations using regex and machine learning parser models.</li>
        <li>Programmatically queries global scholarly databases—specifically CrossRef, Semantic Scholar, and OpenAlex.</li>
        <li>Verifies whether the DOI, authors, journal, volume, and publication year match an active, indexed academic record.</li>
        <li>Flags any unverifiable or partially matching citations with a high-confidence "Hallucination Warning," giving educators concrete, unassailable evidence of generative AI fabrication.</li>
      </ol>
      
      <h3 style={{ marginTop: '32px' }}>Watermarking and Emerging Standards</h3>
      <p>
        As foundational model providers begin implementing cryptographic text watermarking (such as embedding subtle, pseudo-random token selection biases during generation), the Veritas AI Evidence Engine is designed to detect these statistical anomalies. Our framework integrates watermarking decoders, allowing institutions to scan for enterprise-level watermarks from major LLM vendors, providing a layered defense alongside stylometric baseline tracking.
      </p>
    </MarkdownPage>
  );
}
