import React from 'react';
import { DashboardLayout } from '../components/DashboardLayout';
import { AlertTriangle, BookOpen, Check, X } from 'lucide-react';

export function ProfessorFlags() {
  return (
    <DashboardLayout role="professor">
      <div style={{ marginBottom: '24px' }}>
        <h1 style={{ fontSize: '1.8rem', fontWeight: 600, marginBottom: '8px' }}>Flagged Content & Triage</h1>
        <p style={{ color: 'var(--text-secondary)' }}>Review high-risk submissions, citation hallucinations, and stylometric shifts.</p>
      </div>

      <div className="dash-grid">
        <div className="metric-card" style={{ gridColumn: 'span 12', display: 'flex', gap: '24px' }}>
          
          <div style={{ flex: 1, borderRight: '1px solid var(--border-color)', paddingRight: '24px' }}>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 500, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <AlertTriangle size={18} color="#e53e3e" /> Active Triage Queue (2)
            </h3>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <div style={{ padding: '16px', borderRadius: '8px', border: '1px solid var(--accent-blue)', background: 'rgba(66, 153, 225, 0.05)', cursor: 'pointer' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                  <span style={{ fontWeight: 600, fontSize: '0.9rem' }}>Alex Johnson • Final Thesis</span>
                  <span style={{ color: '#e53e3e', fontSize: '0.8rem', fontWeight: 600 }}>High Risk</span>
                </div>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Citation Hallucination detected in Reference [12]. Stylometric shift in Chapter 3.</p>
              </div>

              <div style={{ padding: '16px', borderRadius: '8px', border: '1px solid var(--border-color)', background: 'var(--bg-primary)', cursor: 'pointer', opacity: 0.7 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                  <span style={{ fontWeight: 600, fontSize: '0.9rem' }}>David Chen • Lab Report</span>
                  <span style={{ color: 'var(--accent-orange)', fontSize: '0.8rem', fontWeight: 600 }}>Medium Risk</span>
                </div>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Unusual structural layout and vocabulary complexity spike.</p>
              </div>
            </div>
          </div>

          <div style={{ flex: 1.5 }}>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 500, marginBottom: '16px' }}>Detailed Analysis: Alex Johnson</h3>
            
            <div style={{ background: 'var(--bg-primary)', padding: '20px', borderRadius: '8px', border: '1px solid var(--border-color)', marginBottom: '24px' }}>
              <h4 style={{ fontSize: '0.95rem', fontWeight: 600, marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <BookOpen size={16} color="var(--accent-purple)" /> Citation Verification Report
              </h4>
              <p style={{ fontSize: '0.9rem', color: 'var(--text-primary)', lineHeight: 1.6, marginBottom: '16px' }}>
                "Recent studies in pedagogical integration of LLMs (Smith et al., 2025) suggest that <span style={{ background: 'rgba(229, 62, 62, 0.2)', padding: '2px 4px', borderRadius: '4px' }}>transparent disclosure reduces academic dishonesty by 40%.</span>"
              </p>
              <div style={{ background: 'var(--bg-secondary)', padding: '12px', borderRadius: '6px', borderLeft: '3px solid #e53e3e' }}>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}><strong>System Note:</strong> The citation "Smith et al., 2025" does not exist in any major academic database (Crossref, Semantic Scholar). Highly likely to be a hallucinated reference generated by an LLM.</p>
              </div>
            </div>

            <div style={{ display: 'flex', gap: '12px' }}>
              <button style={{ flex: 1, background: '#e53e3e', color: 'white', border: 'none', padding: '10px', borderRadius: '6px', fontWeight: 500, cursor: 'pointer', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '8px' }}>
                <X size={16} /> Escalate to Integrity Case
              </button>
              <button style={{ flex: 1, background: 'var(--accent-orange)', color: 'white', border: 'none', padding: '10px', borderRadius: '6px', fontWeight: 500, cursor: 'pointer', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '8px' }}>
                Schedule Oral Defense
              </button>
              <button style={{ flex: 1, background: 'var(--bg-tertiary)', color: 'var(--text-primary)', border: '1px solid var(--border-color)', padding: '10px', borderRadius: '6px', fontWeight: 500, cursor: 'pointer', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '8px' }}>
                <Check size={16} /> Dismiss Flag
              </button>
            </div>
          </div>

        </div>
      </div>
    </DashboardLayout>
  );
}
